---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: omada-node-01
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: omada-cluster
    networks:
      - name: omada-cluster
  - name: omada-node-02
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: omada-cluster
    networks:
      - name: omada-cluster
  - name: omada-node-03
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: omada-cluster
    networks:
      - name: omada-cluster
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  check_sequence:
    - dependency
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - converge
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
