---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: omada01
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    docker_networks:
      - name: omada-cluster
        ipam_config:
          - subnet: "10.3.1.0/24"
            gateway: "10.3.1.254"
    networks:
      - name: omada-cluster
        ipv4_address: "10.3.1.1"
    etc_hosts: "{'omada02': '10.3.1.2', 'omada03': '10.3.1.3'}"
  - name: omada02
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: omada-cluster
        ipv4_address: "10.3.1.2"
    etc_hosts: "{'omada01': '10.3.1.1', 'omada03': '10.3.1.3'}"
  - name: omada03
    groups:
      - omada_cluster
    image: ${MOLECULE_IMAGE:-trfore/docker-ubuntu2204-systemd}
    command: ${MOLECULE_COMMAND:-""}
    tmpfs:
      - /run
      - /tmp
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    networks:
      - name: omada-cluster
        ipv4_address: "10.3.1.3"
    etc_hosts: "{'omada01': '10.3.1.1', 'omada02': '10.3.1.2'}"
provisioner:
  name: ansible
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
verifier:
  name: ansible
scenario:
  create_sequence:
    - dependency
    - create
  check_sequence:
    - dependency
    - destroy
    - create
    - converge
    - check
    - destroy
  converge_sequence:
    - dependency
    - create
    - converge
  destroy_sequence:
    - dependency
    - destroy
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - destroy
