name: CI
on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "**.md"
      - "LICENSE"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow}}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  format:
    uses: trfore/ansible-role/.github/workflows/format.yml@main

  lint:
    needs:
      - format
    uses: trfore/ansible-role/.github/workflows/lint_ansible.yml@main

  test:
    needs:
      - format
      - lint
    strategy:
      fail-fast: false
      matrix:
        distro: [debian10, ubuntu2004] # limited to MongoDB 4 matrix
        experimental: [false]
        molecule_scenario: ["-s default"]
        include:
          - distro: ubuntu2004
            experimental: true
            molecule_scenario: "-s ubuntu-jre8"
          - distro: centos8
            experimental: true
            molecule_scenario: "-s default"
    uses: ./.github/workflows/test.yml
    with:
      distro: ${{ matrix.distro }}
      experimental: ${{ matrix.experimental }}
      molecule_scenario: ${{ matrix.molecule_scenario }}
      requirements_file: "requirements/dev-requirements.txt"

  check:
    needs:
      - format
      - lint
      - test
    runs-on: ubuntu-latest
    steps:
      - run: >-
          python -c "assert set([
          '${{ needs.format.result }}',
          '${{ needs.lint.result }}',
          '${{ needs.test.result }}',
          ]) == {'success'}"
